branches:
  only:
    - develop
environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '7'
    - nodejs_version: '8'
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install
matrix:
  fast_finish: true
build: off
shallow_clone: true
test_script:
  - node --version
  - npm --version
  - npm run build
  - npm run test
  #- node tools/test-watch.js
